### ISSUE TITLE
Question about how to open a database with two tables and automatic join

### ISSUE THREAD

**Issue by marckp** [pmqs/BerkeleyDB#6]
Hello Paul,
I'm not sure you are the right person to contact so forgive me if I've reached out to you incorrectly. But, I have perl scripts that use BerkeleyDB perl module. I can't remember which version I used but the last upgrade I performed was to create a database consisting of two tables. When accessed with an appropriate key, the interface would automatically perform a join between the two tables and return the appropriate records. I can't remember where I saw this capability documented, but I think it was on cpam. Somehow the upgraded scripts were lost, but I have scripts that were preped for the grade. I just need to be reminded how to open the files for this kind of query. Can you direct me to the proper documentation for this. A apologize for this kind of trivial request, but I'm desperate.

Thank you for your consideration,
Marc

**Comment by pmqs** [comment]
Hey Marc,

look in https://github.com/pmqs/BerkeleyDB/blob/master/t/join.t for inspiration

**Comment by pmqs** [comment]
You seem to have got past this issue if you've been able to create https://github.com/pmqs/BerkeleyDB/issues/7, so I'm closing this one.
