### ISSUE TITLE
LICENSE BerkeleyDB under AGPL-3.0 to match Oracle's berkeleydb license?

### ISSUE THREAD

**Issue by JasonCoombs** [pmqs/BerkeleyDB#8]
Your work making berkeleydb available from perl scripts for decades (!) is remarkable. Thank you for doing this important work.

Will you consider revising the LICENSE for Perl-BerkeleyDB to match the AGPL-3.0 license supported by Oracle for berkeleydb?

See Oracle's AGPL-3.0, here: https://www.oracle.com/downloads/licenses/berkeleydb-oslicense.html

Also, this repository should conform to GitHub's recommendation; clearly identifying the LICENSE applicable to this source code.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

As you know, the only file in this repository that currently addresses the question of licensing is your BerkeleyDB.pod which is somewhat confusing to read presently, and you have quoted an old FAQ published by Oracle that contained a logical error. There was never a requirement for "software that uses Berkeley DB" (the free berkeleydb database software from Oracle) to be freely redistributable, nor must such software apply the same license (AGPL) as Berkeley DB. That logical error must have been written into the FAQ long ago by somebody who was new to GNU copyleft, free software, and open source at the time the bad thinking occurred.

Oracle's current FAQ contains this:

```
Does the move to the AGPL open source license affect customers who purchased a commercial license?
No. If you own a commercial license, you can continue to download and use new releases of Berkeley DB
under the terms of your commercial license. Berkeley DB continues to be dual license, open source or
commercial. The open source license has changed from the (proprietary) Sleepycat license to the
(industry standard) AGPL.
```

See: https://www.oracle.com/database/technologies/berkeleydb-db-faq.html#DoesthemovetotheAGPLopensourcelicenseaffectcustomerswhopurchasedacommerciallicense

Any software that is derived from Oracle's Berkeley DB must be licensed under the AGPL, but merely using Berkeley DB as the database in your application does not create a derivative work. Redistributing the source code of Berkeley DB along with your own software which creates a Berkeley DB database likewise does not cause you to be obligated to release your source code under the AGPL. Naturally, we want everyone to use the AGPL at all times for all new software development but not everybody does nor can they in every case even if they wanted to do so.

Developers who build software that merely uses your perl BerkeleyDB aren't obligated to apply a license to their source code at all, as you know, not even if they distribute a copy of your source code along with their own to be "open" source (open as in "closed source" but we get to look at the copyright-protected unlicensable-but-transparent work of a closed-source proprietary software vendor) without applying any open source or free software license to the published-under-copyright source code.

Applying the standard straight-forward GNU Affero license to BerkeleyDB instead of inventing your own "free software" license, as you did historically, would clear up this entire question, forever. As the only person who has ever owned the copyright to BerkeleyDB you are able to make this change of license and apply it retroactively if you wish. (please do)

Quoting below from: https://github.com/pmqs/BerkeleyDB/blob/master/BerkeleyDB.pod

```
COPYRIGHT

Copyright (c) 1997-2020 Paul Marquess. All rights reserved. This program
is free software; you can redistribute it and/or modify it under the
same terms as Perl itself.

Although BerkeleyDB is covered by the Perl license, the library it
makes use of, namely Berkeley DB, is not. Berkeley DB has its own
copyright and its own license. Please take the time to read it.

Here are few words taken from the Berkeley DB FAQ at
http://www.oracle.com/technology/products/berkeley-db/db/index.html regarding the license:

    Do I have to license DB to use it in Perl scripts?

    No. The Berkeley DB license requires that software that uses
    Berkeley DB be freely redistributable. In the case of Perl, that
    software is Perl, and not your scripts. Any Perl scripts that you
    write are your property, including scripts that make use of Berkeley
    DB. Neither the Perl license nor the Berkeley DB license
    place any restriction on what you may do with them.

If you are in any doubt about the license situation, contact either the
Berkeley DB authors or the author of BerkeleyDB.
```

**Comment by pmqs** [comment]
Hey Jason,

the intention with the licensing of my code was to use the standard Perl license. The wording in the module was written years ago, when Perl was young and the license issue wasn't foremost in peoples minds. 

Since then Perl has created a more formal Perl license -- see  https://dev.perl.org/licenses/artistic.html

I really do need to add a LICENSE file into github, but I'd prefer to use the new perl one.

**Comment by pmqs** [comment]
Module version 0.65 has updated license wording (0fb21f12d1938f0cd5c3cfe2f674f0c41863fb55)
